parameters:
#    maith_newsletter.example.class: Maith\NewsletterBundle\Example

services:
#    maith_newsletter.example:
#        class: %maith_newsletter.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    maith_new_letter.user_logged:
        class: Maith\NewsletterBundle\Listener\NewsLetterListener
        arguments: [@doctrine.orm.entity_manager, @logger]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 400 }